/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { configurationsCreateConfiguration } from "../../funcs/configurationsCreateConfiguration.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: components.PostConfigurationRequest$inboundSchema,
};

export const tool$configurationsCreateConfiguration: ToolDefinition<
  typeof args
> = {
  name: "configurations-create-configuration",
  description: `Create a new configuration`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await configurationsCreateConfiguration(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
