/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { configurationsGetConfigurations } from "../../funcs/configurationsGetConfigurations.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  project: z.string(),
  env: operations.Env$inboundSchema.optional(),
  name: z.string().optional(),
};

export const tool$configurationsGetConfigurations: ToolDefinition<typeof args> =
  {
    name: "configurations-get-configurations",
    description: `Retrieve a list of configurations`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] = await configurationsGetConfigurations(
        client,
        args.project,
        args.env,
        args.name,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
