/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { datapointsUpdateDatapoint } from "../../funcs/datapointsUpdateDatapoint.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  updateDatapointRequest: components.UpdateDatapointRequest$inboundSchema,
  id: z.string(),
};

export const tool$datapointsUpdateDatapoint: ToolDefinition<typeof args> = {
  name: "datapoints-update-datapoint",
  description: `Update a specific datapoint`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await datapointsUpdateDatapoint(
      client,
      args.updateDatapointRequest,
      args.id,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
