/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { datasetsAddDatapoints } from "../../funcs/datasetsAddDatapoints.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  requestBody: operations.AddDatapointsRequestBody$inboundSchema,
  datasetId: z.string(),
};

export const tool$datasetsAddDatapoints: ToolDefinition<typeof args> = {
  name: "datasets-add-datapoints",
  description: `Add datapoints to a dataset`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await datasetsAddDatapoints(
      client,
      args.requestBody,
      args.datasetId,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
