/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { datapointsGetDatapoints } from "../../funcs/datapointsGetDatapoints.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  project: z.string(),
  datapointIds: z.array(z.string()).optional(),
  datasetName: z.string().optional(),
};

export const tool$datapointsGetDatapoints: ToolDefinition<typeof args> = {
  name: "datapoints-get-datapoints",
  description: `Retrieve a list of datapoints`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await datapointsGetDatapoints(
      client,
      args.project,
      args.datapointIds,
      args.datasetName,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
