/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { datasetsUpdateDataset } from "../../funcs/datasetsUpdateDataset.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: components.DatasetUpdate$inboundSchema,
};

export const tool$datasetsUpdateDataset: ToolDefinition<typeof args> = {
  name: "datasets-update-dataset",
  description: `Update a dataset`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await datasetsUpdateDataset(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
