/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { eventsUpdateEvent } from "../../funcs/eventsUpdateEvent.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.UpdateEventRequestBody$inboundSchema,
};

export const tool$eventsUpdateEvent: ToolDefinition<typeof args> = {
  name: "events-update-event",
  description: `Update an event`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await eventsUpdateEvent(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
