/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { eventsCreateEventBatch } from "../../funcs/eventsCreateEventBatch.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.CreateEventBatchRequestBody$inboundSchema,
};

export const tool$eventsCreateEventBatch: ToolDefinition<typeof args> = {
  name: "events-create-event-batch",
  description: `Create a batch of events

Please refer to our instrumentation guide for detailed information`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await eventsCreateEventBatch(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
