/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { experimentsGetRuns } from "../../funcs/experimentsGetRuns.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  project: z.string().optional(),
};

export const tool$experimentsGetRuns: ToolDefinition<typeof args> = {
  name: "experiments-get-runs",
  description: `Get a list of evaluation runs`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await experimentsGetRuns(
      client,
      args.project,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
