/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { experimentsUpdateRun } from "../../funcs/experimentsUpdateRun.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  updateRunRequest: components.UpdateRunRequest$inboundSchema,
  runId: z.string(),
};

export const tool$experimentsUpdateRun: ToolDefinition<typeof args> = {
  name: "experiments-update-run",
  description: `Update an evaluation run`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await experimentsUpdateRun(
      client,
      args.updateRunRequest,
      args.runId,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
