/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { metricsCreateMetric } from "../../funcs/metricsCreateMetric.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: components.Metric$inboundSchema,
};

export const tool$metricsCreateMetric: ToolDefinition<typeof args> = {
  name: "metrics-create-metric",
  description: `Create a new metric

Add a new metric`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await metricsCreateMetric(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
