/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { projectsDeleteProject } from "../../funcs/projectsDeleteProject.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  name: z.string(),
};

export const tool$projectsDeleteProject: ToolDefinition<typeof args> = {
  name: "projects-delete-project",
  description: `Delete a project`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await projectsDeleteProject(
      client,
      args.name,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
