/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Configurations } from "./configurations.js";
import { Datapoints } from "./datapoints.js";
import { Datasets } from "./datasets.js";
import { Events } from "./events.js";
import { Experiments } from "./experiments.js";
import { Metrics } from "./metrics.js";
import { Projects } from "./projects.js";
import { Session } from "./session.js";
import { Tools } from "./tools.js";

export class HoneyHive extends ClientSDK {
  private _session?: Session;
  get session(): Session {
    return (this._session ??= new Session(this._options));
  }

  private _events?: Events;
  get events(): Events {
    return (this._events ??= new Events(this._options));
  }

  private _metrics?: Metrics;
  get metrics(): Metrics {
    return (this._metrics ??= new Metrics(this._options));
  }

  private _tools?: Tools;
  get tools(): Tools {
    return (this._tools ??= new Tools(this._options));
  }

  private _datapoints?: Datapoints;
  get datapoints(): Datapoints {
    return (this._datapoints ??= new Datapoints(this._options));
  }

  private _datasets?: Datasets;
  get datasets(): Datasets {
    return (this._datasets ??= new Datasets(this._options));
  }

  private _projects?: Projects;
  get projects(): Projects {
    return (this._projects ??= new Projects(this._options));
  }

  private _experiments?: Experiments;
  get experiments(): Experiments {
    return (this._experiments ??= new Experiments(this._options));
  }

  private _configurations?: Configurations;
  get configurations(): Configurations {
    return (this._configurations ??= new Configurations(this._options));
  }
}
