/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../internal/utils";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

export class CreateToolResult extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "insertedId" })
    insertedId?: string;
}

/**
 * Tool successfully created
 */
export class CreateToolResponseBody extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "result" })
    @Type(() => CreateToolResult)
    result?: CreateToolResult;
}

export class CreateToolResponse extends SpeakeasyBase {
    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse: AxiosResponse;

    /**
     * Tool successfully created
     */
    @SpeakeasyMetadata()
    object?: CreateToolResponseBody;
}
