/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../internal/utils";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

export class CreateDatapointResult extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "insertedId" })
    insertedId?: string;
}

/**
 * Datapoint successfully created
 */
export class CreateDatapointResponseBody extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "result" })
    @Type(() => CreateDatapointResult)
    result?: CreateDatapointResult;
}

export class CreateDatapointResponse extends SpeakeasyBase {
    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse: AxiosResponse;

    /**
     * Datapoint successfully created
     */
    @SpeakeasyMetadata()
    object?: CreateDatapointResponseBody;
}
