/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteMetricRequest = {
  metricId: string;
};

/** @internal */
export const DeleteMetricRequest$inboundSchema: z.ZodType<
  DeleteMetricRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  metric_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "metric_id": "metricId",
  });
});

/** @internal */
export type DeleteMetricRequest$Outbound = {
  metric_id: string;
};

/** @internal */
export const DeleteMetricRequest$outboundSchema: z.ZodType<
  DeleteMetricRequest$Outbound,
  z.ZodTypeDef,
  DeleteMetricRequest
> = z.object({
  metricId: z.string(),
}).transform((v) => {
  return remap$(v, {
    metricId: "metric_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteMetricRequest$ {
  /** @deprecated use `DeleteMetricRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteMetricRequest$inboundSchema;
  /** @deprecated use `DeleteMetricRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteMetricRequest$outboundSchema;
  /** @deprecated use `DeleteMetricRequest$Outbound` instead. */
  export type Outbound = DeleteMetricRequest$Outbound;
}

export function deleteMetricRequestToJSON(
  deleteMetricRequest: DeleteMetricRequest,
): string {
  return JSON.stringify(
    DeleteMetricRequest$outboundSchema.parse(deleteMetricRequest),
  );
}

export function deleteMetricRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteMetricRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteMetricRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteMetricRequest' from JSON`,
  );
}
