/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../internal/utils";
import * as components from "../../models/components";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

/**
 * Type of the dataset - "evaluation" or "fine-tuning"
 */
export enum GetDatasetsQueryParamType {
    Evaluation = "evaluation",
    FineTuning = "fine-tuning",
}

export class GetDatasetsRequest extends SpeakeasyBase {
    /**
     * Project ID associated with the datasets
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=project" })
    project: string;

    /**
     * Type of the dataset - "evaluation" or "fine-tuning"
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=type" })
    type?: GetDatasetsQueryParamType;

    /**
     * Unique dataset ID for filtering specific dataset
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=dataset_id" })
    datasetId?: string;
}

/**
 * Successful response
 */
export class GetDatasetsResponseBody extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: components.Dataset })
    @Expose({ name: "datasets" })
    @Type(() => components.Dataset)
    datasets?: components.Dataset[];
}

export class GetDatasetsResponse extends SpeakeasyBase {
    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse: AxiosResponse;

    /**
     * Successful response
     */
    @SpeakeasyMetadata()
    object?: GetDatasetsResponseBody;
}
