/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetRunRequest = {
  runId: string;
};

/** @internal */
export const GetRunRequest$inboundSchema: z.ZodType<
  GetRunRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  run_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "run_id": "runId",
  });
});

/** @internal */
export type GetRunRequest$Outbound = {
  run_id: string;
};

/** @internal */
export const GetRunRequest$outboundSchema: z.ZodType<
  GetRunRequest$Outbound,
  z.ZodTypeDef,
  GetRunRequest
> = z.object({
  runId: z.string(),
}).transform((v) => {
  return remap$(v, {
    runId: "run_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetRunRequest$ {
  /** @deprecated use `GetRunRequest$inboundSchema` instead. */
  export const inboundSchema = GetRunRequest$inboundSchema;
  /** @deprecated use `GetRunRequest$outboundSchema` instead. */
  export const outboundSchema = GetRunRequest$outboundSchema;
  /** @deprecated use `GetRunRequest$Outbound` instead. */
  export type Outbound = GetRunRequest$Outbound;
}
