/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../internal/utils";
import { AxiosResponse } from "axios";
import { Expose } from "class-transformer";

export class PostFineTunedModelsRequestBody extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "task" })
    task?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "dataset_id" })
    datasetId?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "model" })
    model?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "hyperparams" })
    hyperparams?: string;
}

/**
 * Success
 */
export class PostFineTunedModelsResponseBody extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status?: string;
}

export class PostFineTunedModelsResponse extends SpeakeasyBase {
    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse: AxiosResponse;

    /**
     * Success
     */
    @SpeakeasyMetadata()
    object?: PostFineTunedModelsResponseBody;
}
