/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type UpdateConfigurationRequest = {
    /**
     * Configuration ID like `6638187d505c6812e4043f24`
     */
    id: string;
    putConfigurationRequest: components.PutConfigurationRequest;
};

/** @internal */
export const UpdateConfigurationRequest$inboundSchema: z.ZodType<
    UpdateConfigurationRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        id: z.string(),
        PutConfigurationRequest: components.PutConfigurationRequest$inboundSchema,
    })
    .transform((v) => {
        return remap$(v, {
            PutConfigurationRequest: "putConfigurationRequest",
        });
    });

/** @internal */
export type UpdateConfigurationRequest$Outbound = {
    id: string;
    PutConfigurationRequest: components.PutConfigurationRequest$Outbound;
};

/** @internal */
export const UpdateConfigurationRequest$outboundSchema: z.ZodType<
    UpdateConfigurationRequest$Outbound,
    z.ZodTypeDef,
    UpdateConfigurationRequest
> = z
    .object({
        id: z.string(),
        putConfigurationRequest: components.PutConfigurationRequest$outboundSchema,
    })
    .transform((v) => {
        return remap$(v, {
            putConfigurationRequest: "PutConfigurationRequest",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateConfigurationRequest$ {
    /** @deprecated use `UpdateConfigurationRequest$inboundSchema` instead. */
    export const inboundSchema = UpdateConfigurationRequest$inboundSchema;
    /** @deprecated use `UpdateConfigurationRequest$outboundSchema` instead. */
    export const outboundSchema = UpdateConfigurationRequest$outboundSchema;
    /** @deprecated use `UpdateConfigurationRequest$Outbound` instead. */
    export type Outbound = UpdateConfigurationRequest$Outbound;
}
