/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Type of datapoint - "evaluation" or "fine-tuning"
 */
export enum CreateDatapointRequestType {
    Evaluation = "evaluation",
    FineTuning = "fine-tuning",
}

export class CreateDatapointRequest extends SpeakeasyBase {
    /**
     * Expected output JSON object for the datapoint
     */
    @SpeakeasyMetadata()
    @Expose({ name: "ground_truth" })
    groundTruth?: Record<string, any>;

    /**
     * Arbitrary JSON object containing the inputs for the datapoint
     */
    @SpeakeasyMetadata()
    @Expose({ name: "inputs" })
    inputs: Record<string, any>;

    /**
     * Ids of all datasets that include the datapoint
     */
    @SpeakeasyMetadata()
    @Expose({ name: "linked_datasets" })
    linkedDatasets?: string[];

    /**
     * Ids of evaluations where the datapoint is included
     */
    @SpeakeasyMetadata()
    @Expose({ name: "linked_evals" })
    linkedEvals?: string[];

    /**
     * Event id for the event from which the datapoint was created
     */
    @SpeakeasyMetadata()
    @Expose({ name: "linked_event" })
    linkedEvent?: string;

    /**
     * Any additional metadata for the datapoint
     */
    @SpeakeasyMetadata()
    @Expose({ name: "metadata" })
    metadata?: Record<string, any>;

    /**
     * UUID for the project to which the datapoint belongs
     */
    @SpeakeasyMetadata()
    @Expose({ name: "project" })
    project: string;

    /**
     * Whether the datapoint is saved or detected
     */
    @SpeakeasyMetadata()
    @Expose({ name: "saved" })
    saved?: boolean;

    /**
     * Type of datapoint - "evaluation" or "fine-tuning"
     */
    @SpeakeasyMetadata()
    @Expose({ name: "type" })
    type: CreateDatapointRequestType;
}
