/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../internal/utils";
import { Expose } from "class-transformer";

export enum CreateToolRequestType {
    Function = "function",
    Tool = "tool",
}

export class CreateToolRequest extends SpeakeasyBase {
    /**
     * Name of the project associated with this tool
     */
    @SpeakeasyMetadata()
    @Expose({ name: "task" })
    task: string;

    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name: string;

    @SpeakeasyMetadata()
    @Expose({ name: "description" })
    description?: string;

    /**
     * These can be function call params or plugin call params
     */
    @SpeakeasyMetadata()
    @Expose({ name: "parameters" })
    parameters: Record<string, any>;

    @SpeakeasyMetadata()
    @Expose({ name: "type" })
    type: CreateToolRequestType;
}
