/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../internal/utils";
import { Expose } from "class-transformer";

export class CreateModelEvent extends SpeakeasyBase {
    /**
     * Project associated with the event
     */
    @SpeakeasyMetadata()
    @Expose({ name: "project" })
    project: string;

    /**
     * Model name
     */
    @SpeakeasyMetadata()
    @Expose({ name: "model" })
    model: string;

    /**
     * Model provider
     */
    @SpeakeasyMetadata()
    @Expose({ name: "provider" })
    provider: string;

    /**
     * Messages passed to the model
     */
    @SpeakeasyMetadata()
    @Expose({ name: "messages" })
    messages: Record<string, any>[];

    /**
     * Final output JSON of the event
     */
    @SpeakeasyMetadata()
    @Expose({ name: "response" })
    response: Record<string, any>;

    /**
     * How long the event took in milliseconds
     */
    @SpeakeasyMetadata()
    @Expose({ name: "duration" })
    duration: number;

    /**
     * Usage statistics of the model
     */
    @SpeakeasyMetadata()
    @Expose({ name: "usage" })
    usage: Record<string, any>;

    /**
     * Cost of the model completion
     */
    @SpeakeasyMetadata()
    @Expose({ name: "cost" })
    cost?: number;

    /**
     * Any error description if event failed
     */
    @SpeakeasyMetadata()
    @Expose({ name: "error" })
    error?: string;

    /**
     * Source of the event - production, staging, etc
     */
    @SpeakeasyMetadata()
    @Expose({ name: "source" })
    source?: string;

    /**
     * Name of the event
     */
    @SpeakeasyMetadata()
    @Expose({ name: "event_name" })
    eventName?: string;

    /**
     * Hyperparameters used for the model
     */
    @SpeakeasyMetadata()
    @Expose({ name: "hyperparameters" })
    hyperparameters?: Record<string, any>;

    /**
     * Template used for the model
     */
    @SpeakeasyMetadata()
    @Expose({ name: "template" })
    template?: Record<string, any>[];

    /**
     * Inputs for the template
     */
    @SpeakeasyMetadata()
    @Expose({ name: "template_inputs" })
    templateInputs?: Record<string, any>;

    /**
     * Tools used for the model
     */
    @SpeakeasyMetadata()
    @Expose({ name: "tools" })
    tools?: Record<string, any>[];

    /**
     * Tool choice for the model
     */
    @SpeakeasyMetadata()
    @Expose({ name: "tool_choice" })
    toolChoice?: string;

    /**
     * Response format for the model
     */
    @SpeakeasyMetadata()
    @Expose({ name: "response_format" })
    responseFormat?: Record<string, any>;
}
