/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../internal/utils";
import { Expose, Type } from "class-transformer";

/**
 * Updated metadata to track for the dataset
 */
export class DatasetUpdateMetadata extends SpeakeasyBase {}

export class DatasetUpdate extends SpeakeasyBase {
    /**
     * Updated list of datapoint ids for the dataset
     */
    @SpeakeasyMetadata()
    @Expose({ name: "datapoints" })
    datapoints?: string[];

    /**
     * The unique identifier of the dataset being updated
     */
    @SpeakeasyMetadata()
    @Expose({ name: "dataset_id" })
    datasetId: string;

    /**
     * Updated description for the dataset
     */
    @SpeakeasyMetadata()
    @Expose({ name: "description" })
    description?: string;

    /**
     * Updated list of unique evaluation run ids to be associated with this dataset
     */
    @SpeakeasyMetadata()
    @Expose({ name: "linked_evals" })
    linkedEvals?: string[];

    /**
     * Updated metadata to track for the dataset
     */
    @SpeakeasyMetadata()
    @Expose({ name: "metadata" })
    @Type(() => DatasetUpdateMetadata)
    metadata?: DatasetUpdateMetadata;

    /**
     * Updated name for the dataset
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "num_points" })
    numPoints?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "saved" })
    saved?: boolean;
}
