/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../internal/utils";
import { Expose } from "class-transformer";

export class EvaluationUpdateRequest extends SpeakeasyBase {
    /**
     * The name of the evaluation
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    /**
     * The description of the evaluation
     */
    @SpeakeasyMetadata()
    @Expose({ name: "description" })
    description?: string;

    /**
     * The task for which the evaluation is being created
     */
    @SpeakeasyMetadata()
    @Expose({ name: "task" })
    task?: string;

    /**
     * The prompts for which the evaluation is being created
     */
    @SpeakeasyMetadata()
    @Expose({ name: "prompts" })
    prompts?: Record<string, any>[];

    /**
     * The name of the dataset for which the evaluation is being created
     */
    @SpeakeasyMetadata()
    @Expose({ name: "datasetName" })
    datasetName?: string;

    /**
     * The dataset for which the evaluation is being created
     */
    @SpeakeasyMetadata()
    @Expose({ name: "dataset" })
    dataset?: Record<string, any>[];

    /**
     * The metrics that are computed for the completions
     */
    @SpeakeasyMetadata()
    @Expose({ name: "metrics" })
    metrics?: Record<string, any>[][];

    /**
     * The metric summary of the evaluation
     */
    @SpeakeasyMetadata()
    @Expose({ name: "summary" })
    summary?: Record<string, any>[];

    /**
     * The completions for prompts that are being evaluated
     */
    @SpeakeasyMetadata()
    @Expose({ name: "generations" })
    generations?: Record<string, any>[];

    /**
     * The results of the evaluation
     */
    @SpeakeasyMetadata()
    @Expose({ name: "results" })
    results?: Record<string, any>[];

    /**
     * Whether each result was accepted
     */
    @SpeakeasyMetadata()
    @Expose({ name: "accepted" })
    accepted?: boolean[];

    /**
     * The comments for the evaluation
     */
    @SpeakeasyMetadata()
    @Expose({ name: "comments" })
    comments?: Record<string, any>[];

    /**
     * The user running the evaluation
     */
    @SpeakeasyMetadata()
    @Expose({ name: "user" })
    user?: string;
}
