/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../internal/utils";
import { Expose, Transform, Type } from "class-transformer";

/**
 * The results of the evaluation (including pass/fails and metric aggregations)
 */
export class Results extends SpeakeasyBase {}

export enum EvaluationRunStatus {
    Pending = "pending",
    Completed = "completed",
}

export class EvaluationRun extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "run_id" })
    runId?: string;

    /**
     * The UUID of the project this run is associated with
     */
    @SpeakeasyMetadata()
    @Expose({ name: "project" })
    project?: string;

    /**
     * The date and time the run was created
     */
    @SpeakeasyMetadata()
    @Expose({ name: "created_at" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    createdAt?: Date;

    /**
     * The UUIDs of the sessions/events this run is associated with
     */
    @SpeakeasyMetadata()
    @Expose({ name: "event_ids" })
    eventIds?: string[];

    /**
     * The UUID of the dataset this run is associated with
     */
    @SpeakeasyMetadata()
    @Expose({ name: "dataset_id" })
    datasetId?: string;

    /**
     * The UUIDs of the datapoints from the original dataset this run is associated with
     */
    @SpeakeasyMetadata()
    @Expose({ name: "datapoint_ids" })
    datapointIds?: string[];

    /**
     * The results of the evaluation (including pass/fails and metric aggregations)
     */
    @SpeakeasyMetadata()
    @Expose({ name: "results" })
    @Type(() => Results)
    results?: Results;

    /**
     * The configuration being used for this run
     */
    @SpeakeasyMetadata()
    @Expose({ name: "configuration" })
    configuration?: Record<string, any>;

    /**
     * Additional metadata for the run
     */
    @SpeakeasyMetadata()
    @Expose({ name: "metadata" })
    metadata?: Record<string, any>;

    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status?: EvaluationRunStatus;

    /**
     * The name of the run to be displayed
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;
}
