/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../internal/utils";
import { Expose, Transform } from "class-transformer";

/**
 * The response object for a fine-tuned model
 */
export class FineTunedModelResponse extends SpeakeasyBase {
    /**
     * The ID of the fine-tuned model
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;

    /**
     * The object type of the fine-tuned model
     */
    @SpeakeasyMetadata()
    @Expose({ name: "object" })
    object?: string;

    /**
     * The model used for fine-tuning
     */
    @SpeakeasyMetadata()
    @Expose({ name: "model" })
    model?: string;

    /**
     * The timestamp of when the fine-tuned model was created
     */
    @SpeakeasyMetadata()
    @Expose({ name: "created_at" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    createdAt?: Date;

    /**
     * The timestamp of when the fine-tuned model was last updated
     */
    @SpeakeasyMetadata()
    @Expose({ name: "updated_at" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    updatedAt?: Date;

    /**
     * The fine-tuned model
     */
    @SpeakeasyMetadata()
    @Expose({ name: "fine_tuned_model" })
    fineTunedModel?: string;

    /**
     * The hyperparameters used for fine-tuning
     */
    @SpeakeasyMetadata()
    @Expose({ name: "hyperparams" })
    hyperparams?: string;

    /**
     * The ID of the organization
     */
    @SpeakeasyMetadata()
    @Expose({ name: "org_id" })
    orgId?: string;

    /**
     * The result files of the fine-tuned model
     */
    @SpeakeasyMetadata()
    @Expose({ name: "result_files" })
    resultFiles?: string;

    /**
     * The status of the fine-tuned model
     */
    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status?: string;

    /**
     * The validation files used for fine-tuning
     */
    @SpeakeasyMetadata()
    @Expose({ name: "validation_files" })
    validationFiles?: string;

    /**
     * The training files used for fine-tuning
     */
    @SpeakeasyMetadata()
    @Expose({ name: "training_files" })
    trainingFiles?: string;
}
