/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../internal/utils";
import { Expose } from "class-transformer";

/**
 * The request object for generating text
 */
export class GenerateQuery extends SpeakeasyBase {
    /**
     * The task for which the generation is being requested
     */
    @SpeakeasyMetadata()
    @Expose({ name: "task" })
    task?: string;

    /**
     * The input variables for the generation
     */
    @SpeakeasyMetadata()
    @Expose({ name: "input" })
    input?: Record<string, any>;

    /**
     * The unique IDs of the prompts to generate from
     */
    @SpeakeasyMetadata()
    @Expose({ name: "prompts" })
    prompts?: string[];

    /**
     * The unique ID of the fine-tuned model to generate from
     */
    @SpeakeasyMetadata()
    @Expose({ name: "model_id" })
    modelId?: string;

    /**
     * The number of generations to be returned
     */
    @SpeakeasyMetadata()
    @Expose({ name: "best_of" })
    bestOf?: number;

    /**
     * The metric used for sorting the generations
     */
    @SpeakeasyMetadata()
    @Expose({ name: "metric" })
    metric?: string;

    /**
     * The sampling method used for generating the generations
     */
    @SpeakeasyMetadata()
    @Expose({ name: "sampling" })
    sampling?: string;

    /**
     * The metadata to track for the generation
     */
    @SpeakeasyMetadata()
    @Expose({ name: "metadata" })
    metadata?: Record<string, any>;

    /**
     * A boolean flag that represents whether you want to generate a streaming output
     */
    @SpeakeasyMetadata()
    @Expose({ name: "stream" })
    stream?: boolean;

    /**
     * The user properties to track for the generation
     */
    @SpeakeasyMetadata()
    @Expose({ name: "user_properties" })
    userProperties?: Record<string, any>;

    /**
     * The source of the generation
     */
    @SpeakeasyMetadata()
    @Expose({ name: "source" })
    source?: string;

    /**
     * The ground truth of the generation
     */
    @SpeakeasyMetadata()
    @Expose({ name: "ground_truth" })
    groundTruth?: string;
}
