/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../internal/utils";
import { EvaluationRun } from "./evaluationrun";
import { Expose, Type } from "class-transformer";

export class GetRunsResponse extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: EvaluationRun })
    @Expose({ name: "evaluations" })
    @Type(() => EvaluationRun)
    evaluations?: EvaluationRun[];
}
