/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../internal/utils";
import { EvaluationRun } from "./evaluationrun";
import { Expose, Type } from "class-transformer";

export class GetRunResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "evaluation" })
    @Type(() => EvaluationRun)
    evaluation?: EvaluationRun;
}
