/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../internal/utils";
import { Expose } from "class-transformer";

export class MetricEdit extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "metric_id" })
    metricId?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "code_snippet" })
    codeSnippet?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "type" })
    type?: string;
}
