/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../internal/utils";
import { SessionEventQuery } from "./sessioneventquery";
import { Expose, Type } from "class-transformer";

/**
 * The response object for a session trace
 */
export class SessionTrace extends SpeakeasyBase {
    /**
     * The trace logs for the session
     */
    @SpeakeasyMetadata({ elemType: SessionEventQuery })
    @Expose({ name: "logs" })
    @Type(() => SessionEventQuery)
    logs?: SessionEventQuery[];
}
