/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../internal/utils";
import { Expose } from "class-transformer";

/**
 * The response object indicating the success of an operation
 */
export class SuccessResponse extends SpeakeasyBase {
    /**
     * Indicates whether the request was successful
     */
    @SpeakeasyMetadata()
    @Expose({ name: "success" })
    success?: boolean;

    /**
     * The ID of the created object
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;
}
