/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../internal/utils";
import { Expose } from "class-transformer";

export class TaskUpdateResponse extends SpeakeasyBase {
    /**
     * Boolean flag representing if the update operation was successful
     */
    @SpeakeasyMetadata()
    @Expose({ name: "acknowledged" })
    acknowledged?: boolean;

    /**
     * Number of modified tasks
     */
    @SpeakeasyMetadata()
    @Expose({ name: "modifiedCount" })
    modifiedCount?: number;

    /**
     * The upserted ID of the task, if id has been changed
     */
    @SpeakeasyMetadata()
    @Expose({ name: "upsertedId" })
    upsertedId?: string;

    /**
     * Number of upserted tasks
     */
    @SpeakeasyMetadata()
    @Expose({ name: "upsertedCount" })
    upsertedCount?: number;

    /**
     * Number of modified tasks
     */
    @SpeakeasyMetadata()
    @Expose({ name: "matchedCount" })
    matchedCount?: number;
}
