/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../internal/utils";
import { DatasetResponse } from "./datasetresponse";
import { FineTunedModelResponse } from "./finetunedmodelresponse";
import { MetricResponse } from "./metricresponse";
import { PromptResponse } from "./promptresponse";
import { Expose, Type } from "class-transformer";

/**
 * The request object for updating a task
 */
export class TaskUpdateQuery extends SpeakeasyBase {
    /**
     * The id of the task being updated
     */
    @SpeakeasyMetadata()
    @Expose({ name: "task_id" })
    taskId?: string;

    /**
     * The new name of the task
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    /**
     * The new type of the task
     */
    @SpeakeasyMetadata()
    @Expose({ name: "type" })
    type?: string;

    /**
     * The new fine-tuned models for the task
     */
    @SpeakeasyMetadata({ elemType: FineTunedModelResponse })
    @Expose({ name: "fine_tuned_models" })
    @Type(() => FineTunedModelResponse)
    fineTunedModels?: FineTunedModelResponse[];

    /**
     * The new prompts for the task
     */
    @SpeakeasyMetadata({ elemType: PromptResponse })
    @Expose({ name: "prompts" })
    @Type(() => PromptResponse)
    prompts?: PromptResponse[];

    /**
     * The new datasets for the task
     */
    @SpeakeasyMetadata({ elemType: DatasetResponse })
    @Expose({ name: "datasets" })
    @Type(() => DatasetResponse)
    datasets?: DatasetResponse[];

    /**
     * The new metrics for the task
     */
    @SpeakeasyMetadata({ elemType: MetricResponse })
    @Expose({ name: "metrics" })
    @Type(() => MetricResponse)
    metrics?: MetricResponse[];
}
