/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../internal/utils";
import { Expose } from "class-transformer";

export class UpdateDatapointRequest extends SpeakeasyBase {
    /**
     * Arbitrary JSON object containing the inputs for the datapoint
     */
    @SpeakeasyMetadata()
    @Expose({ name: "inputs" })
    inputs?: Record<string, any>;

    /**
     * Conversation history associated with the datapoint
     */
    @SpeakeasyMetadata()
    @Expose({ name: "history" })
    history?: Record<string, any>[];

    /**
     * Expected output JSON object for the datapoint
     */
    @SpeakeasyMetadata()
    @Expose({ name: "ground_truth" })
    groundTruth?: Record<string, any>;

    /**
     * Ids of evaluations where the datapoint is included
     */
    @SpeakeasyMetadata()
    @Expose({ name: "linked_evals" })
    linkedEvals?: string[];

    /**
     * Ids of all datasets that include the datapoint
     */
    @SpeakeasyMetadata()
    @Expose({ name: "linked_datasets" })
    linkedDatasets?: string[];

    /**
     * Any additional metadata for the datapoint
     */
    @SpeakeasyMetadata()
    @Expose({ name: "metadata" })
    metadata?: Record<string, any>;
}
