name: Generate
permissions:
  checks: write
  contents: write
  pull-requests: write
  statuses: write
"on":
  workflow_dispatch:
    inputs:
      force:
        description: Force generation of SDKs
        type: boolean
        default: false
  schedule:
    - cron: 0 0 * * *
jobs:
  generate:
    uses: speakeasy-api/sdk-generation-action/.github/workflows/workflow-executor.yaml@v15
    with:
      force: ${{ github.event.inputs.force }}
      mode: pr
      speakeasy_version: latest
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      openapi_doc_auth_token: ${{ secrets.SPEAKEASY_API_KEY }}
      speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}

  run_tests:
    needs: generate
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -f tests/Dockerfile . -t my-test

      - name: Run Docker image
        run: |
          docker run -e HH_API_KEY="${{ secrets.HH_API_KEY }}" \
                     -e HH_PROJECT_NAME="${{ secrets.HH_PROJECT }}" \
                     -e HH_API_URL="${{ secrets.HH_API_URL }}" \
                     -e HH_PROJECT_ID="${{ secrets.HH_PROJECT_ID }}" \
                     -e HH_DATASET="${{ secrets.HH_DATASET }}" \
                     -e OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}" \
                     -e SERP_API_KEY="${{ secrets.SERP_API_KEY }}" \
                     -t my-test
